### ISSUE TITLE
Support for Sublime 3

### ISSUE THREAD

**Issue by asaf** [mulesoft/raml-sublime-plugin#3]
Hey,

Any chance to support Sublime 3?

Thanks.

**Comment by blakeembrey** [comment]
Hey! Did you have a specific issue come up? I've been using it with Sublime Text 3 for a while now without any issues.

**Comment by asaf** [comment]
Hey, can't see the plugin in the plugin list ! so I was sure it's only
compatible with 2.

**Comment by blakeembrey** [comment]
Hmm, not sure what's up then. It's in the package repository https://packagecontrol.io/packages/RAML%20Syntax%20Highlighter with ST3 support and I installed it using the installation menu.

**Comment by asaf** [comment]
@blakeembrey Oh well, probably something on my side then, thanks ! :-)
