### ISSUE TITLE
RAML 1.0 Support

### ISSUE THREAD

**Issue by jcenturion** [mulesoft/raml-sublime-plugin#8]
Do you have plans for supporting RAML 1.0?

**Comment by miclf** [comment]
I would also appreciate to know that.

**Comment by FedeAmdan** [comment]
Hi @jcenturion @miclf , I have just uploaded a new tmLanguage file which contains a lot of bug fixing and is prepared to be used with RAML 1.0. It will be automatically downloaded to your text editors the next time you open them, if you are using Package control. Please share any feedback with us, thanks for using the sublime plugin!
